services:
  - type: web
    plan: free
    name: course_app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn course_app.asgi:application -k uvicorn.workers.UvicornWorker"